server:
  port: ${SERVER_PORT:8081}
  address: 0.0.0.0

spring:
  application:
    name: spring-webflux-nosql
  data:
    mongodb:
      database: ${MONGO_DATABASE}
      uri: ${MONGO_URI}

springdoc:
  api-docs:
    enabled: true
    path: /api-docs
  swagger-ui:
    enabled: true
    path: /swagger-ui.html  # http://localhost:8081/swagger-ui.html