server:
  port: 8081

spring:
  application:
    name: ms-spring-webflux-nosql
  data:
    mongodb:
      database: nosql
      uri: mongodb+srv://juan:12345@cluster0.zdl9n.mongodb.net/?appName=Cluster0

springdoc:
  api-docs:
    enabled: true
    path: /api-docs
  swagger-ui:
    enabled: true
    path: /swagger-ui.html