server:
  port: 8081

spring:
  application:
    name: ms-spring-webflux-nosql
  data:
    mongodb:
      database: vitrocco
      uri: mongodb+srv://victor2025:victor2025@cluster0.w1ywt.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0