# kubectl apply -f 00-juan-condori-secret.yml
apiVersion: v1
kind: Secret
metadata:
  name: 00-juan-condori-secret
  namespace: 00-juan-condori-namespace
type: Opaque
data:
  DATABASE_URL: cjJkYmM6cG9zdGdyZXM6Ly9iYXR5ci5kYi5lbGVwaGFudHNxbC5jb206NTQzMi9ta3lodHRycA==   # en Base64
  DATABASE_USERNAME: bWt5aHR0cnA=   # en Base64
  DATABASE_PASSWORD: QnJQM0pqenlOX0NEWU9iTUIzQWdUVXM1V2RmYklQVzc=   # en Base64


#echo -n "demo123" | base64
#echo "ZGVtbzEyMw==" | base64 --decode