# kubectl apply -f juan-condori-00-secret.yml
# kubectl delete -f juan-condori-00-secret.yml
apiVersion: v1
kind: Secret
metadata:
  name: juan-condori-00-secret
  namespace: juan-condori-00-namespace
type: Opaque
data:
  MONGO_DATABASE: ZGF0YWJhc2VfY2xvdWQ=   # en Base64
  MONGO_URI: bW9uZ29kYitzcnY6Ly9qdWFuOjEyMzQ1QGNsdXN0ZXIwLnpkbDluLm1vbmdvZGIubmV0Lz9hcHBOYW1lPUNsdXN0ZXIw   # en Base64
  SERVER_PORT: ODA4MQ==

# CONVERTIR A BASE64 CON PAGINA WEB
# https://base64.guru/converter


# CONVERTIR A BASE64 CON COMANDOS
# echo -n "demo123" | base64
# echo "ZGVtbzEyMw==" | base64 --decode